// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.11.4
// source: data-source.proto

package ds_grpc

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type DSRawResponse_ErrorCode int32

const (
	DSRawResponse_NONE        DSRawResponse_ErrorCode = 0 // no error
	DSRawResponse_BAD_REQUEST DSRawResponse_ErrorCode = 1 // crash of compilation, logs will show stacktrace
	DSRawResponse_NO_DATA     DSRawResponse_ErrorCode = 2 // no such module
)

// Enum value maps for DSRawResponse_ErrorCode.
var (
	DSRawResponse_ErrorCode_name = map[int32]string{
		0: "NONE",
		1: "BAD_REQUEST",
		2: "NO_DATA",
	}
	DSRawResponse_ErrorCode_value = map[string]int32{
		"NONE":        0,
		"BAD_REQUEST": 1,
		"NO_DATA":     2,
	}
)

func (x DSRawResponse_ErrorCode) Enum() *DSRawResponse_ErrorCode {
	p := new(DSRawResponse_ErrorCode)
	*p = x
	return p
}

func (x DSRawResponse_ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DSRawResponse_ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_data_source_proto_enumTypes[0].Descriptor()
}

func (DSRawResponse_ErrorCode) Type() protoreflect.EnumType {
	return &file_data_source_proto_enumTypes[0]
}

func (x DSRawResponse_ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DSRawResponse_ErrorCode.Descriptor instead.
func (DSRawResponse_ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_data_source_proto_rawDescGZIP(), []int{1, 0}
}

type DSAccessPath struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address []byte `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // AccountAddress
	Path    []byte `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *DSAccessPath) Reset() {
	*x = DSAccessPath{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_source_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DSAccessPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DSAccessPath) ProtoMessage() {}

func (x *DSAccessPath) ProtoReflect() protoreflect.Message {
	mi := &file_data_source_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DSAccessPath.ProtoReflect.Descriptor instead.
func (*DSAccessPath) Descriptor() ([]byte, []int) {
	return file_data_source_proto_rawDescGZIP(), []int{0}
}

func (x *DSAccessPath) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *DSAccessPath) GetPath() []byte {
	if x != nil {
		return x.Path
	}
	return nil
}

type DSRawResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Blob         []byte                  `protobuf:"bytes,1,opt,name=blob,proto3" json:"blob,omitempty"`
	ErrorCode    DSRawResponse_ErrorCode `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3,enum=ds_grpc.DSRawResponse_ErrorCode" json:"error_code,omitempty"`
	ErrorMessage string                  `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // error message from libra, empty if ErrorCode::None
}

func (x *DSRawResponse) Reset() {
	*x = DSRawResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_source_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DSRawResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DSRawResponse) ProtoMessage() {}

func (x *DSRawResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_source_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DSRawResponse.ProtoReflect.Descriptor instead.
func (*DSRawResponse) Descriptor() ([]byte, []int) {
	return file_data_source_proto_rawDescGZIP(), []int{1}
}

func (x *DSRawResponse) GetBlob() []byte {
	if x != nil {
		return x.Blob
	}
	return nil
}

func (x *DSRawResponse) GetErrorCode() DSRawResponse_ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return DSRawResponse_NONE
}

func (x *DSRawResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type DSAccessPaths struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paths []*DSAccessPath `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
}

func (x *DSAccessPaths) Reset() {
	*x = DSAccessPaths{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_source_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DSAccessPaths) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DSAccessPaths) ProtoMessage() {}

func (x *DSAccessPaths) ProtoReflect() protoreflect.Message {
	mi := &file_data_source_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DSAccessPaths.ProtoReflect.Descriptor instead.
func (*DSAccessPaths) Descriptor() ([]byte, []int) {
	return file_data_source_proto_rawDescGZIP(), []int{2}
}

func (x *DSAccessPaths) GetPaths() []*DSAccessPath {
	if x != nil {
		return x.Paths
	}
	return nil
}

type DSRawResponses struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Blobs [][]byte `protobuf:"bytes,1,rep,name=blobs,proto3" json:"blobs,omitempty"`
}

func (x *DSRawResponses) Reset() {
	*x = DSRawResponses{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_source_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DSRawResponses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DSRawResponses) ProtoMessage() {}

func (x *DSRawResponses) ProtoReflect() protoreflect.Message {
	mi := &file_data_source_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DSRawResponses.ProtoReflect.Descriptor instead.
func (*DSRawResponses) Descriptor() ([]byte, []int) {
	return file_data_source_proto_rawDescGZIP(), []int{3}
}

func (x *DSRawResponses) GetBlobs() [][]byte {
	if x != nil {
		return x.Blobs
	}
	return nil
}

var File_data_source_proto protoreflect.FileDescriptor

var file_data_source_proto_rawDesc = []byte{
	0x0a, 0x11, 0x64, 0x61, 0x74, 0x61, 0x2d, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x64, 0x73, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x22, 0x3c, 0x0a, 0x0c,
	0x44, 0x53, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x50, 0x61, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0xbe, 0x01, 0x0a, 0x0d, 0x44,
	0x53, 0x52, 0x61, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x62, 0x6c, 0x6f, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6c, 0x6f, 0x62,
	0x12, 0x3f, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x64, 0x73, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x44,
	0x53, 0x52, 0x61, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x33, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0f, 0x0a,
	0x0b, 0x42, 0x41, 0x44, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x10, 0x01, 0x12, 0x0b,
	0x0a, 0x07, 0x4e, 0x4f, 0x5f, 0x44, 0x41, 0x54, 0x41, 0x10, 0x02, 0x22, 0x3c, 0x0a, 0x0d, 0x44,
	0x53, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x50, 0x61, 0x74, 0x68, 0x73, 0x12, 0x2b, 0x0a, 0x05,
	0x70, 0x61, 0x74, 0x68, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x64, 0x73,
	0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x53, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x50, 0x61,
	0x74, 0x68, 0x52, 0x05, 0x70, 0x61, 0x74, 0x68, 0x73, 0x22, 0x26, 0x0a, 0x0e, 0x44, 0x53, 0x52,
	0x61, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x62,
	0x6c, 0x6f, 0x62, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x62,
	0x73, 0x32, 0x88, 0x01, 0x0a, 0x09, 0x44, 0x53, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x39, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x52, 0x61, 0x77, 0x12, 0x15, 0x2e, 0x64, 0x73, 0x5f, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x44, 0x53, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x50, 0x61, 0x74, 0x68,
	0x1a, 0x16, 0x2e, 0x64, 0x73, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x53, 0x52, 0x61, 0x77,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0b, 0x4d, 0x75,
	0x6c, 0x74, 0x69, 0x47, 0x65, 0x74, 0x52, 0x61, 0x77, 0x12, 0x16, 0x2e, 0x64, 0x73, 0x5f, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x44, 0x53, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x50, 0x61, 0x74, 0x68,
	0x73, 0x1a, 0x17, 0x2e, 0x64, 0x73, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x53, 0x52, 0x61,
	0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_data_source_proto_rawDescOnce sync.Once
	file_data_source_proto_rawDescData = file_data_source_proto_rawDesc
)

func file_data_source_proto_rawDescGZIP() []byte {
	file_data_source_proto_rawDescOnce.Do(func() {
		file_data_source_proto_rawDescData = protoimpl.X.CompressGZIP(file_data_source_proto_rawDescData)
	})
	return file_data_source_proto_rawDescData
}

var file_data_source_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_data_source_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_data_source_proto_goTypes = []interface{}{
	(DSRawResponse_ErrorCode)(0), // 0: ds_grpc.DSRawResponse.ErrorCode
	(*DSAccessPath)(nil),         // 1: ds_grpc.DSAccessPath
	(*DSRawResponse)(nil),        // 2: ds_grpc.DSRawResponse
	(*DSAccessPaths)(nil),        // 3: ds_grpc.DSAccessPaths
	(*DSRawResponses)(nil),       // 4: ds_grpc.DSRawResponses
}
var file_data_source_proto_depIdxs = []int32{
	0, // 0: ds_grpc.DSRawResponse.error_code:type_name -> ds_grpc.DSRawResponse.ErrorCode
	1, // 1: ds_grpc.DSAccessPaths.paths:type_name -> ds_grpc.DSAccessPath
	1, // 2: ds_grpc.DSService.GetRaw:input_type -> ds_grpc.DSAccessPath
	3, // 3: ds_grpc.DSService.MultiGetRaw:input_type -> ds_grpc.DSAccessPaths
	2, // 4: ds_grpc.DSService.GetRaw:output_type -> ds_grpc.DSRawResponse
	4, // 5: ds_grpc.DSService.MultiGetRaw:output_type -> ds_grpc.DSRawResponses
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_data_source_proto_init() }
func file_data_source_proto_init() {
	if File_data_source_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_data_source_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DSAccessPath); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_source_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DSRawResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_source_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DSAccessPaths); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_source_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DSRawResponses); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_data_source_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_data_source_proto_goTypes,
		DependencyIndexes: file_data_source_proto_depIdxs,
		EnumInfos:         file_data_source_proto_enumTypes,
		MessageInfos:      file_data_source_proto_msgTypes,
	}.Build()
	File_data_source_proto = out.File
	file_data_source_proto_rawDesc = nil
	file_data_source_proto_goTypes = nil
	file_data_source_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DSServiceClient is the client API for DSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DSServiceClient interface {
	GetRaw(ctx context.Context, in *DSAccessPath, opts ...grpc.CallOption) (*DSRawResponse, error)
	MultiGetRaw(ctx context.Context, in *DSAccessPaths, opts ...grpc.CallOption) (*DSRawResponses, error)
}

type dSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDSServiceClient(cc grpc.ClientConnInterface) DSServiceClient {
	return &dSServiceClient{cc}
}

func (c *dSServiceClient) GetRaw(ctx context.Context, in *DSAccessPath, opts ...grpc.CallOption) (*DSRawResponse, error) {
	out := new(DSRawResponse)
	err := c.cc.Invoke(ctx, "/ds_grpc.DSService/GetRaw", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dSServiceClient) MultiGetRaw(ctx context.Context, in *DSAccessPaths, opts ...grpc.CallOption) (*DSRawResponses, error) {
	out := new(DSRawResponses)
	err := c.cc.Invoke(ctx, "/ds_grpc.DSService/MultiGetRaw", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DSServiceServer is the server API for DSService service.
type DSServiceServer interface {
	GetRaw(context.Context, *DSAccessPath) (*DSRawResponse, error)
	MultiGetRaw(context.Context, *DSAccessPaths) (*DSRawResponses, error)
}

// UnimplementedDSServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDSServiceServer struct {
}

func (*UnimplementedDSServiceServer) GetRaw(context.Context, *DSAccessPath) (*DSRawResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRaw not implemented")
}
func (*UnimplementedDSServiceServer) MultiGetRaw(context.Context, *DSAccessPaths) (*DSRawResponses, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MultiGetRaw not implemented")
}

func RegisterDSServiceServer(s *grpc.Server, srv DSServiceServer) {
	s.RegisterService(&_DSService_serviceDesc, srv)
}

func _DSService_GetRaw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DSAccessPath)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DSServiceServer).GetRaw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ds_grpc.DSService/GetRaw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DSServiceServer).GetRaw(ctx, req.(*DSAccessPath))
	}
	return interceptor(ctx, in, info, handler)
}

func _DSService_MultiGetRaw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DSAccessPaths)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DSServiceServer).MultiGetRaw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ds_grpc.DSService/MultiGetRaw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DSServiceServer).MultiGetRaw(ctx, req.(*DSAccessPaths))
	}
	return interceptor(ctx, in, info, handler)
}

var _DSService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ds_grpc.DSService",
	HandlerType: (*DSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRaw",
			Handler:    _DSService_GetRaw_Handler,
		},
		{
			MethodName: "MultiGetRaw",
			Handler:    _DSService_MultiGetRaw_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "data-source.proto",
}
