// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.11.4
// source: common-types.proto

package types

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Type of contract argument.
type VMTypeTag int32

const (
	VMTypeTag_Bool    VMTypeTag = 0 // Bool 0x0 - false, 0x1 - true.
	VMTypeTag_U64     VMTypeTag = 1 // Uint64. Little-endian unsigned 64 bits integer.
	VMTypeTag_Vector  VMTypeTag = 2 // Vector of bytes.
	VMTypeTag_Address VMTypeTag = 3 // Address, in bech32 form. 20 bytes.
	VMTypeTag_U8      VMTypeTag = 4 // U8
	VMTypeTag_U128    VMTypeTag = 5 // U128 Little-endian unsigned 128 bits integer.
)

// Enum value maps for VMTypeTag.
var (
	VMTypeTag_name = map[int32]string{
		0: "Bool",
		1: "U64",
		2: "Vector",
		3: "Address",
		4: "U8",
		5: "U128",
	}
	VMTypeTag_value = map[string]int32{
		"Bool":    0,
		"U64":     1,
		"Vector":  2,
		"Address": 3,
		"U8":      4,
		"U128":    5,
	}
)

func (x VMTypeTag) Enum() *VMTypeTag {
	p := new(VMTypeTag)
	*p = x
	return p
}

func (x VMTypeTag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VMTypeTag) Descriptor() protoreflect.EnumDescriptor {
	return file_common_types_proto_enumTypes[0].Descriptor()
}

func (VMTypeTag) Type() protoreflect.EnumType {
	return &file_common_types_proto_enumTypes[0]
}

func (x VMTypeTag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VMTypeTag.Descriptor instead.
func (VMTypeTag) EnumDescriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{0}
}

var File_common_types_proto protoreflect.FileDescriptor

var file_common_types_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2d, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2a, 0x49, 0x0a, 0x09, 0x56,
	0x4d, 0x54, 0x79, 0x70, 0x65, 0x54, 0x61, 0x67, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x6f, 0x6f, 0x6c,
	0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x55, 0x36, 0x34, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x56,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x10, 0x03, 0x12, 0x06, 0x0a, 0x02, 0x55, 0x38, 0x10, 0x04, 0x12, 0x08, 0x0a, 0x04,
	0x55, 0x31, 0x32, 0x38, 0x10, 0x05, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_types_proto_rawDescOnce sync.Once
	file_common_types_proto_rawDescData = file_common_types_proto_rawDesc
)

func file_common_types_proto_rawDescGZIP() []byte {
	file_common_types_proto_rawDescOnce.Do(func() {
		file_common_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_types_proto_rawDescData)
	})
	return file_common_types_proto_rawDescData
}

var file_common_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_types_proto_goTypes = []interface{}{
	(VMTypeTag)(0), // 0: types.VMTypeTag
}
var file_common_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_types_proto_init() }
func file_common_types_proto_init() {
	if File_common_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_types_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_types_proto_goTypes,
		DependencyIndexes: file_common_types_proto_depIdxs,
		EnumInfos:         file_common_types_proto_enumTypes,
	}.Build()
	File_common_types_proto = out.File
	file_common_types_proto_rawDesc = nil
	file_common_types_proto_goTypes = nil
	file_common_types_proto_depIdxs = nil
}
