// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0-devel
// 	protoc        v3.11.4
// source: vm.proto

package vm_grpc

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Status of contract execution.
type ContractStatus int32

const (
	ContractStatus_Discard ContractStatus = 0 // If transaction should be ignored, because of error.
	ContractStatus_Keep    ContractStatus = 1 // If we keep transaction and write write_set.
)

// Enum value maps for ContractStatus.
var (
	ContractStatus_name = map[int32]string{
		0: "Discard",
		1: "Keep",
	}
	ContractStatus_value = map[string]int32{
		"Discard": 0,
		"Keep":    1,
	}
)

func (x ContractStatus) Enum() *ContractStatus {
	p := new(ContractStatus)
	*p = x
	return p
}

func (x ContractStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContractStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_vm_proto_enumTypes[0].Descriptor()
}

func (ContractStatus) Type() protoreflect.EnumType {
	return &file_vm_proto_enumTypes[0]
}

func (x ContractStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContractStatus.Descriptor instead.
func (ContractStatus) EnumDescriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{0}
}

// Type of contract argument.
type VMTypeTag int32

const (
	VMTypeTag_Bool    VMTypeTag = 0 // Bool 0x0 - false, 0x1 - true.
	VMTypeTag_U64     VMTypeTag = 1 // Uint64. Little-endian unsigned 64 bits integer.
	VMTypeTag_Vector  VMTypeTag = 2 // Vector of bytes.
	VMTypeTag_Address VMTypeTag = 3 // Address, in bech32 form. 20 bytes.
	VMTypeTag_U8      VMTypeTag = 4 // U8
	VMTypeTag_U128    VMTypeTag = 5 // U128 Little-endian unsigned 128 bits integer.
)

// Enum value maps for VMTypeTag.
var (
	VMTypeTag_name = map[int32]string{
		0: "Bool",
		1: "U64",
		2: "Vector",
		3: "Address",
		4: "U8",
		5: "U128",
	}
	VMTypeTag_value = map[string]int32{
		"Bool":    0,
		"U64":     1,
		"Vector":  2,
		"Address": 3,
		"U8":      4,
		"U128":    5,
	}
)

func (x VMTypeTag) Enum() *VMTypeTag {
	p := new(VMTypeTag)
	*p = x
	return p
}

func (x VMTypeTag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VMTypeTag) Descriptor() protoreflect.EnumDescriptor {
	return file_vm_proto_enumTypes[1].Descriptor()
}

func (VMTypeTag) Type() protoreflect.EnumType {
	return &file_vm_proto_enumTypes[1]
}

func (x VMTypeTag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VMTypeTag.Descriptor instead.
func (VMTypeTag) EnumDescriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{1}
}

type LcsType int32

const (
	LcsType_LcsBool    LcsType = 0 // Bool
	LcsType_LcsU64     LcsType = 1 // Uint64
	LcsType_LcsVector  LcsType = 2 // Vector of bytes.
	LcsType_LcsAddress LcsType = 3 // Address, in bech32 form
	LcsType_LcsU8      LcsType = 4 // U8
	LcsType_LcsU128    LcsType = 5 // U128
	LcsType_LcsSigner  LcsType = 6 // Signer.
	LcsType_LcsStruct  LcsType = 7 // Struct.
)

// Enum value maps for LcsType.
var (
	LcsType_name = map[int32]string{
		0: "LcsBool",
		1: "LcsU64",
		2: "LcsVector",
		3: "LcsAddress",
		4: "LcsU8",
		5: "LcsU128",
		6: "LcsSigner",
		7: "LcsStruct",
	}
	LcsType_value = map[string]int32{
		"LcsBool":    0,
		"LcsU64":     1,
		"LcsVector":  2,
		"LcsAddress": 3,
		"LcsU8":      4,
		"LcsU128":    5,
		"LcsSigner":  6,
		"LcsStruct":  7,
	}
)

func (x LcsType) Enum() *LcsType {
	p := new(LcsType)
	*p = x
	return p
}

func (x LcsType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LcsType) Descriptor() protoreflect.EnumDescriptor {
	return file_vm_proto_enumTypes[2].Descriptor()
}

func (LcsType) Type() protoreflect.EnumType {
	return &file_vm_proto_enumTypes[2]
}

func (x LcsType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LcsType.Descriptor instead.
func (LcsType) EnumDescriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{2}
}

// Write set operation type.
type VmWriteOp int32

const (
	VmWriteOp_Value    VmWriteOp = 0 // Insert or update value
	VmWriteOp_Deletion VmWriteOp = 1 // Delete.
)

// Enum value maps for VmWriteOp.
var (
	VmWriteOp_name = map[int32]string{
		0: "Value",
		1: "Deletion",
	}
	VmWriteOp_value = map[string]int32{
		"Value":    0,
		"Deletion": 1,
	}
)

func (x VmWriteOp) Enum() *VmWriteOp {
	p := new(VmWriteOp)
	*p = x
	return p
}

func (x VmWriteOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VmWriteOp) Descriptor() protoreflect.EnumDescriptor {
	return file_vm_proto_enumTypes[3].Descriptor()
}

func (VmWriteOp) Type() protoreflect.EnumType {
	return &file_vm_proto_enumTypes[3]
}

func (x VmWriteOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VmWriteOp.Descriptor instead.
func (VmWriteOp) EnumDescriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{3}
}

// Status of code contract execution.
type VMStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MajorStatus uint64 `protobuf:"varint,1,opt,name=major_status,json=majorStatus,proto3" json:"major_status,omitempty"` // Major status.
	SubStatus   uint64 `protobuf:"varint,2,opt,name=sub_status,json=subStatus,proto3" json:"sub_status,omitempty"`       // Sub status if needed (optional).
	Message     string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                             // Message with error details if needed (optional).
}

func (x *VMStatus) Reset() {
	*x = VMStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VMStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMStatus) ProtoMessage() {}

func (x *VMStatus) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMStatus.ProtoReflect.Descriptor instead.
func (*VMStatus) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{0}
}

func (x *VMStatus) GetMajorStatus() uint64 {
	if x != nil {
		return x.MajorStatus
	}
	return 0
}

func (x *VMStatus) GetSubStatus() uint64 {
	if x != nil {
		return x.SubStatus
	}
	return 0
}

func (x *VMStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

/// Full name of the structure.
type StructIdent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address    []byte    `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`                         // address of module owner
	Module     string    `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`                           // module name.
	Name       string    `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                               // name of structure.
	TypeParams []*LcsTag `protobuf:"bytes,4,rep,name=type_params,json=typeParams,proto3" json:"type_params,omitempty"` // Structure type parameters.
}

func (x *StructIdent) Reset() {
	*x = StructIdent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StructIdent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructIdent) ProtoMessage() {}

func (x *StructIdent) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructIdent.ProtoReflect.Descriptor instead.
func (*StructIdent) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{1}
}

func (x *StructIdent) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *StructIdent) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *StructIdent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StructIdent) GetTypeParams() []*LcsTag {
	if x != nil {
		return x.TypeParams
	}
	return nil
}

type LcsTag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TypeTag     LcsType      `protobuf:"varint,1,opt,name=type_tag,json=typeTag,proto3,enum=vm_grpc.LcsType" json:"type_tag,omitempty"` // type tag.
	VectorType  *LcsTag      `protobuf:"bytes,2,opt,name=vector_type,json=vectorType,proto3" json:"vector_type,omitempty"`              // vector type. Has a non-null value if the type_tag is equal to a LcsVector.
	StructIdent *StructIdent `protobuf:"bytes,3,opt,name=struct_ident,json=structIdent,proto3" json:"struct_ident,omitempty"`           // struct identifier. Has a non-null value if the type_tag is equal to a LcsStruct.
}

func (x *LcsTag) Reset() {
	*x = LcsTag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LcsTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LcsTag) ProtoMessage() {}

func (x *LcsTag) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LcsTag.ProtoReflect.Descriptor instead.
func (*LcsTag) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{2}
}

func (x *LcsTag) GetTypeTag() LcsType {
	if x != nil {
		return x.TypeTag
	}
	return LcsType_LcsBool
}

func (x *LcsTag) GetVectorType() *LcsTag {
	if x != nil {
		return x.VectorType
	}
	return nil
}

func (x *LcsTag) GetStructIdent() *StructIdent {
	if x != nil {
		return x.StructIdent
	}
	return nil
}

/// Module identifier.
type ModuleIdent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address []byte `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // module address.
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`       // module name.
}

func (x *ModuleIdent) Reset() {
	*x = ModuleIdent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vm_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModuleIdent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleIdent) ProtoMessage() {}

func (x *ModuleIdent) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleIdent.ProtoReflect.Descriptor instead.
func (*ModuleIdent) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{3}
}

func (x *ModuleIdent) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *ModuleIdent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// VM event returns after contract execution.
type VMEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SenderAddress []byte       `protobuf:"bytes,1,opt,name=sender_address,json=senderAddress,proto3" json:"sender_address,omitempty"` // Event sender address.
	SenderModule  *ModuleIdent `protobuf:"bytes,2,opt,name=sender_module,json=senderModule,proto3" json:"sender_module,omitempty"`    // sender module.
	EventType     *LcsTag      `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`             // Type of value inside event.
	EventData     []byte       `protobuf:"bytes,4,opt,name=event_data,json=eventData,proto3" json:"event_data,omitempty"`             // Event data in bytes to parse.
}

func (x *VMEvent) Reset() {
	*x = VMEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vm_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VMEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMEvent) ProtoMessage() {}

func (x *VMEvent) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMEvent.ProtoReflect.Descriptor instead.
func (*VMEvent) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{4}
}

func (x *VMEvent) GetSenderAddress() []byte {
	if x != nil {
		return x.SenderAddress
	}
	return nil
}

func (x *VMEvent) GetSenderModule() *ModuleIdent {
	if x != nil {
		return x.SenderModule
	}
	return nil
}

func (x *VMEvent) GetEventType() *LcsTag {
	if x != nil {
		return x.EventType
	}
	return nil
}

func (x *VMEvent) GetEventData() []byte {
	if x != nil {
		return x.EventData
	}
	return nil
}

// Storage path
type VMAccessPath struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address []byte `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // account address.
	Path    []byte `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`       // storage path.
}

func (x *VMAccessPath) Reset() {
	*x = VMAccessPath{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vm_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VMAccessPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMAccessPath) ProtoMessage() {}

func (x *VMAccessPath) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMAccessPath.ProtoReflect.Descriptor instead.
func (*VMAccessPath) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{5}
}

func (x *VMAccessPath) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *VMAccessPath) GetPath() []byte {
	if x != nil {
		return x.Path
	}
	return nil
}

// VM value should be passed before execution and return after execution (with opcodes), write_set in nutshell.
type VMValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  VmWriteOp     `protobuf:"varint,2,opt,name=type,proto3,enum=vm_grpc.VmWriteOp" json:"type,omitempty"` // Type of operation
	Value []byte        `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`                       // Value returns from vm.
	Path  *VMAccessPath `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`                         // Access path.
}

func (x *VMValue) Reset() {
	*x = VMValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vm_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VMValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMValue) ProtoMessage() {}

func (x *VMValue) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMValue.ProtoReflect.Descriptor instead.
func (*VMValue) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{6}
}

func (x *VMValue) GetType() VmWriteOp {
	if x != nil {
		return x.Type
	}
	return VmWriteOp_Value
}

func (x *VMValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *VMValue) GetPath() *VMAccessPath {
	if x != nil {
		return x.Path
	}
	return nil
}

// Contract arguments.
type VMArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  VMTypeTag `protobuf:"varint,1,opt,name=type,proto3,enum=vm_grpc.VMTypeTag" json:"type,omitempty"` // Argument type.
	Value []byte    `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`                       // Argument value.
}

func (x *VMArgs) Reset() {
	*x = VMArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vm_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VMArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMArgs) ProtoMessage() {}

func (x *VMArgs) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMArgs.ProtoReflect.Descriptor instead.
func (*VMArgs) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{7}
}

func (x *VMArgs) GetType() VMTypeTag {
	if x != nil {
		return x.Type
	}
	return VMTypeTag_Bool
}

func (x *VMArgs) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// Publish module.
type VMPublishModule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address      []byte `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`                                  // owner of contract (module) or script executor.
	MaxGasAmount uint64 `protobuf:"varint,2,opt,name=max_gas_amount,json=maxGasAmount,proto3" json:"max_gas_amount,omitempty"` // maximal total gas specified by wallet to spend for this transaction.
	GasUnitPrice uint64 `protobuf:"varint,3,opt,name=gas_unit_price,json=gasUnitPrice,proto3" json:"gas_unit_price,omitempty"` // maximal price can be paid per gas.
	Code         []byte `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`                                        // compiled contract code.
}

func (x *VMPublishModule) Reset() {
	*x = VMPublishModule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vm_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VMPublishModule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMPublishModule) ProtoMessage() {}

func (x *VMPublishModule) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMPublishModule.ProtoReflect.Descriptor instead.
func (*VMPublishModule) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{8}
}

func (x *VMPublishModule) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *VMPublishModule) GetMaxGasAmount() uint64 {
	if x != nil {
		return x.MaxGasAmount
	}
	return 0
}

func (x *VMPublishModule) GetGasUnitPrice() uint64 {
	if x != nil {
		return x.GasUnitPrice
	}
	return 0
}

func (x *VMPublishModule) GetCode() []byte {
	if x != nil {
		return x.Code
	}
	return nil
}

// VM contract object to process.
type VMExecuteScript struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address      []byte         `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`                                  // owner of contract (module) or script executor.
	MaxGasAmount uint64         `protobuf:"varint,2,opt,name=max_gas_amount,json=maxGasAmount,proto3" json:"max_gas_amount,omitempty"` // maximal total gas specified by wallet to spend for this transaction.
	GasUnitPrice uint64         `protobuf:"varint,3,opt,name=gas_unit_price,json=gasUnitPrice,proto3" json:"gas_unit_price,omitempty"` // maximal price can be paid per gas.
	Code         []byte         `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`                                        // compiled contract code.
	TypeParams   []*StructIdent `protobuf:"bytes,7,rep,name=type_params,json=typeParams,proto3" json:"type_params,omitempty"`          // type parameters.
	Args         []*VMArgs      `protobuf:"bytes,8,rep,name=args,proto3" json:"args,omitempty"`                                        // Contract arguments.
}

func (x *VMExecuteScript) Reset() {
	*x = VMExecuteScript{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vm_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VMExecuteScript) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMExecuteScript) ProtoMessage() {}

func (x *VMExecuteScript) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMExecuteScript.ProtoReflect.Descriptor instead.
func (*VMExecuteScript) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{9}
}

func (x *VMExecuteScript) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *VMExecuteScript) GetMaxGasAmount() uint64 {
	if x != nil {
		return x.MaxGasAmount
	}
	return 0
}

func (x *VMExecuteScript) GetGasUnitPrice() uint64 {
	if x != nil {
		return x.GasUnitPrice
	}
	return 0
}

func (x *VMExecuteScript) GetCode() []byte {
	if x != nil {
		return x.Code
	}
	return nil
}

func (x *VMExecuteScript) GetTypeParams() []*StructIdent {
	if x != nil {
		return x.TypeParams
	}
	return nil
}

func (x *VMExecuteScript) GetArgs() []*VMArgs {
	if x != nil {
		return x.Args
	}
	return nil
}

// Response from VM contains write_set, events, gas used and status for specific contract.
type VMExecuteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WriteSet     []*VMValue     `protobuf:"bytes,1,rep,name=write_set,json=writeSet,proto3" json:"write_set,omitempty"`          // using string instead of bytes for now, as map support only ints and strings as keys
	Events       []*VMEvent     `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`                              // list of events executed during contract execution
	GasUsed      uint64         `protobuf:"varint,3,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`            // Gas used during execution.
	Status       ContractStatus `protobuf:"varint,4,opt,name=status,proto3,enum=vm_grpc.ContractStatus" json:"status,omitempty"` // Status of contract execution.
	StatusStruct *VMStatus      `protobuf:"bytes,5,opt,name=statusStruct,proto3" json:"statusStruct,omitempty"`                  // Main status of execution, might contain an error.
}

func (x *VMExecuteResponse) Reset() {
	*x = VMExecuteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vm_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VMExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMExecuteResponse) ProtoMessage() {}

func (x *VMExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMExecuteResponse.ProtoReflect.Descriptor instead.
func (*VMExecuteResponse) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{10}
}

func (x *VMExecuteResponse) GetWriteSet() []*VMValue {
	if x != nil {
		return x.WriteSet
	}
	return nil
}

func (x *VMExecuteResponse) GetEvents() []*VMEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *VMExecuteResponse) GetGasUsed() uint64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *VMExecuteResponse) GetStatus() ContractStatus {
	if x != nil {
		return x.Status
	}
	return ContractStatus_Discard
}

func (x *VMExecuteResponse) GetStatusStruct() *VMStatus {
	if x != nil {
		return x.StatusStruct
	}
	return nil
}

// Compiler API
type SourceFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text    string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`       // utf8 encoded source code with libra/bech32 addresses
	Address []byte `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"` // address of the sender, in bech32 form
}

func (x *SourceFile) Reset() {
	*x = SourceFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vm_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SourceFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceFile) ProtoMessage() {}

func (x *SourceFile) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceFile.ProtoReflect.Descriptor instead.
func (*SourceFile) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{11}
}

func (x *SourceFile) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SourceFile) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

// Compilation unit.
type CompilationUnit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"` // utf8 encoded source code with libra/bech32 addresses
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // name of the unit.
}

func (x *CompilationUnit) Reset() {
	*x = CompilationUnit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vm_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompilationUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompilationUnit) ProtoMessage() {}

func (x *CompilationUnit) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompilationUnit.ProtoReflect.Descriptor instead.
func (*CompilationUnit) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{12}
}

func (x *CompilationUnit) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CompilationUnit) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Compiler API
type SourceFiles struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Units   []*CompilationUnit `protobuf:"bytes,1,rep,name=units,proto3" json:"units,omitempty"`     // Compilation units.
	Address []byte             `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"` // address of the sender, in bech32 form
}

func (x *SourceFiles) Reset() {
	*x = SourceFiles{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vm_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SourceFiles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceFiles) ProtoMessage() {}

func (x *SourceFiles) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceFiles.ProtoReflect.Descriptor instead.
func (*SourceFiles) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{13}
}

func (x *SourceFiles) GetUnits() []*CompilationUnit {
	if x != nil {
		return x.Units
	}
	return nil
}

func (x *SourceFiles) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

// Compiled source.
type CompiledUnit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`         // name of the module/script.
	Bytecode []byte `protobuf:"bytes,2,opt,name=bytecode,proto3" json:"bytecode,omitempty"` // bytecode of the compiled module/script
}

func (x *CompiledUnit) Reset() {
	*x = CompiledUnit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vm_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompiledUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompiledUnit) ProtoMessage() {}

func (x *CompiledUnit) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompiledUnit.ProtoReflect.Descriptor instead.
func (*CompiledUnit) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{14}
}

func (x *CompiledUnit) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CompiledUnit) GetBytecode() []byte {
	if x != nil {
		return x.Bytecode
	}
	return nil
}

type MultipleCompilationResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Units  []*CompiledUnit `protobuf:"bytes,1,rep,name=units,proto3" json:"units,omitempty"`
	Errors []string        `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"` // list of error messages, empty if successful
}

func (x *MultipleCompilationResult) Reset() {
	*x = MultipleCompilationResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vm_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultipleCompilationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipleCompilationResult) ProtoMessage() {}

func (x *MultipleCompilationResult) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipleCompilationResult.ProtoReflect.Descriptor instead.
func (*MultipleCompilationResult) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{15}
}

func (x *MultipleCompilationResult) GetUnits() []*CompiledUnit {
	if x != nil {
		return x.Units
	}
	return nil
}

func (x *MultipleCompilationResult) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type CompilationResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bytecode []byte   `protobuf:"bytes,1,opt,name=bytecode,proto3" json:"bytecode,omitempty"` // bytecode of the compiled module/script
	Errors   []string `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`     // list of error messages, empty if successful
}

func (x *CompilationResult) Reset() {
	*x = CompilationResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vm_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompilationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompilationResult) ProtoMessage() {}

func (x *CompilationResult) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompilationResult.ProtoReflect.Descriptor instead.
func (*CompilationResult) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{16}
}

func (x *CompilationResult) GetBytecode() []byte {
	if x != nil {
		return x.Bytecode
	}
	return nil
}

func (x *CompilationResult) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

// Script Arguments API
type VMScript struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code []byte `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` // bytecode of script
}

func (x *VMScript) Reset() {
	*x = VMScript{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vm_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VMScript) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMScript) ProtoMessage() {}

func (x *VMScript) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMScript.ProtoReflect.Descriptor instead.
func (*VMScript) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{17}
}

func (x *VMScript) GetCode() []byte {
	if x != nil {
		return x.Code
	}
	return nil
}

type Signature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Arguments []VMTypeTag `protobuf:"varint,1,rep,packed,name=arguments,proto3,enum=vm_grpc.VMTypeTag" json:"arguments,omitempty"`
}

func (x *Signature) Reset() {
	*x = Signature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vm_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signature.ProtoReflect.Descriptor instead.
func (*Signature) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{18}
}

func (x *Signature) GetArguments() []VMTypeTag {
	if x != nil {
		return x.Arguments
	}
	return nil
}

var File_vm_proto protoreflect.FileDescriptor

var file_vm_proto_rawDesc = []byte{
	0x0a, 0x08, 0x76, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x76, 0x6d, 0x5f, 0x67,
	0x72, 0x70, 0x63, 0x22, 0x66, 0x0a, 0x08, 0x56, 0x4d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x21, 0x0a, 0x0c, 0x6d, 0x61, 0x6a, 0x6f, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x6d, 0x61, 0x6a, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x75, 0x62, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x73, 0x75, 0x62, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x85, 0x01, 0x0a, 0x0b,
	0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x30, 0x0a, 0x0b, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x76, 0x6d, 0x5f, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x4c, 0x63, 0x73, 0x54, 0x61, 0x67, 0x52, 0x0a, 0x74, 0x79, 0x70, 0x65, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x22, 0xa0, 0x01, 0x0a, 0x06, 0x4c, 0x63, 0x73, 0x54, 0x61, 0x67, 0x12, 0x2b,
	0x0a, 0x08, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x10, 0x2e, 0x76, 0x6d, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x63, 0x73, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x07, 0x74, 0x79, 0x70, 0x65, 0x54, 0x61, 0x67, 0x12, 0x30, 0x0a, 0x0b, 0x76,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x76, 0x6d, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x63, 0x73, 0x54, 0x61,
	0x67, 0x52, 0x0a, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x37, 0x0a,
	0x0c, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x76, 0x6d, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x52, 0x0b, 0x73, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x22, 0x3b, 0x0a, 0x0b, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0xba, 0x01, 0x0a, 0x07, 0x56, 0x4d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12,
	0x25, 0x0a, 0x0e, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x39, 0x0a, 0x0d, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x5f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x76, 0x6d, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x52, 0x0c, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4d, 0x6f, 0x64, 0x75, 0x6c,
	0x65, 0x12, 0x2e, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x76, 0x6d, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x4c, 0x63, 0x73, 0x54, 0x61, 0x67, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x22, 0x3c, 0x0a, 0x0c, 0x56, 0x4d, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x50, 0x61, 0x74, 0x68,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x72,
	0x0a, 0x07, 0x56, 0x4d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x76, 0x6d, 0x5f, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x56, 0x6d, 0x57, 0x72, 0x69, 0x74, 0x65, 0x4f, 0x70, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x29, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x76, 0x6d, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x56, 0x4d, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x50, 0x61, 0x74, 0x68, 0x52, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x22, 0x46, 0x0a, 0x06, 0x56, 0x4d, 0x41, 0x72, 0x67, 0x73, 0x12, 0x26, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x76, 0x6d, 0x5f,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x4d, 0x54, 0x79, 0x70, 0x65, 0x54, 0x61, 0x67, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x8b, 0x01, 0x0a, 0x0f, 0x56,
	0x4d, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x24, 0x0a, 0x0e, 0x6d, 0x61, 0x78, 0x5f,
	0x67, 0x61, 0x73, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0c, 0x6d, 0x61, 0x78, 0x47, 0x61, 0x73, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x24,
	0x0a, 0x0e, 0x67, 0x61, 0x73, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x67, 0x61, 0x73, 0x55, 0x6e, 0x69, 0x74, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0xe7, 0x01, 0x0a, 0x0f, 0x56, 0x4d, 0x45,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x24, 0x0a, 0x0e, 0x6d, 0x61, 0x78, 0x5f, 0x67, 0x61,
	0x73, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c,
	0x6d, 0x61, 0x78, 0x47, 0x61, 0x73, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x24, 0x0a, 0x0e,
	0x67, 0x61, 0x73, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x67, 0x61, 0x73, 0x55, 0x6e, 0x69, 0x74, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x35, 0x0a, 0x0b, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x76, 0x6d,
	0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x52, 0x0a, 0x74, 0x79, 0x70, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x23, 0x0a,
	0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x76, 0x6d,
	0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x4d, 0x41, 0x72, 0x67, 0x73, 0x52, 0x04, 0x61, 0x72,
	0x67, 0x73, 0x22, 0xef, 0x01, 0x0a, 0x11, 0x56, 0x4d, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x09, 0x77, 0x72, 0x69, 0x74,
	0x65, 0x5f, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x76, 0x6d,
	0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x4d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x08, 0x77,
	0x72, 0x69, 0x74, 0x65, 0x53, 0x65, 0x74, 0x12, 0x28, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x76, 0x6d, 0x5f, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x56, 0x4d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x61, 0x73, 0x5f, 0x75, 0x73, 0x65, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x07, 0x67, 0x61, 0x73, 0x55, 0x73, 0x65, 0x64, 0x12, 0x2f, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x76,
	0x6d, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x35, 0x0a,
	0x0c, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x76, 0x6d, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x4d,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0c, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x53, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x22, 0x3a, 0x0a, 0x0a, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x46, 0x69,
	0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x22, 0x39, 0x0a, 0x0f, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55,
	0x6e, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x57, 0x0a, 0x0b, 0x53,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x2e, 0x0a, 0x05, 0x75, 0x6e,
	0x69, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x76, 0x6d, 0x5f, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55,
	0x6e, 0x69, 0x74, 0x52, 0x05, 0x75, 0x6e, 0x69, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x22, 0x3e, 0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x64,
	0x55, 0x6e, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x79, 0x74, 0x65,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x62, 0x79, 0x74, 0x65,
	0x63, 0x6f, 0x64, 0x65, 0x22, 0x60, 0x0a, 0x19, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65,
	0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x2b, 0x0a, 0x05, 0x75, 0x6e, 0x69, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x76, 0x6d, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x69,
	0x6c, 0x65, 0x64, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x05, 0x75, 0x6e, 0x69, 0x74, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x22, 0x47, 0x0a, 0x11, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x62,
	0x79, 0x74, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x62,
	0x79, 0x74, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x22,
	0x1e, 0x0a, 0x08, 0x56, 0x4d, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22,
	0x3d, 0x0a, 0x09, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x30, 0x0a, 0x09,
	0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32,
	0x12, 0x2e, 0x76, 0x6d, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x4d, 0x54, 0x79, 0x70, 0x65,
	0x54, 0x61, 0x67, 0x52, 0x09, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2a, 0x27,
	0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x0b, 0x0a, 0x07, 0x44, 0x69, 0x73, 0x63, 0x61, 0x72, 0x64, 0x10, 0x00, 0x12, 0x08, 0x0a,
	0x04, 0x4b, 0x65, 0x65, 0x70, 0x10, 0x01, 0x2a, 0x49, 0x0a, 0x09, 0x56, 0x4d, 0x54, 0x79, 0x70,
	0x65, 0x54, 0x61, 0x67, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x6f, 0x6f, 0x6c, 0x10, 0x00, 0x12, 0x07,
	0x0a, 0x03, 0x55, 0x36, 0x34, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x56, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x10, 0x03,
	0x12, 0x06, 0x0a, 0x02, 0x55, 0x38, 0x10, 0x04, 0x12, 0x08, 0x0a, 0x04, 0x55, 0x31, 0x32, 0x38,
	0x10, 0x05, 0x2a, 0x77, 0x0a, 0x07, 0x4c, 0x63, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a,
	0x07, 0x4c, 0x63, 0x73, 0x42, 0x6f, 0x6f, 0x6c, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4c, 0x63,
	0x73, 0x55, 0x36, 0x34, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x4c, 0x63, 0x73, 0x56, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x4c, 0x63, 0x73, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x63, 0x73, 0x55, 0x38, 0x10, 0x04,
	0x12, 0x0b, 0x0a, 0x07, 0x4c, 0x63, 0x73, 0x55, 0x31, 0x32, 0x38, 0x10, 0x05, 0x12, 0x0d, 0x0a,
	0x09, 0x4c, 0x63, 0x73, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x10, 0x06, 0x12, 0x0d, 0x0a, 0x09,
	0x4c, 0x63, 0x73, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x10, 0x07, 0x2a, 0x24, 0x0a, 0x09, 0x56,
	0x6d, 0x57, 0x72, 0x69, 0x74, 0x65, 0x4f, 0x70, 0x12, 0x09, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x10,
	0x01, 0x32, 0x5c, 0x0a, 0x11, 0x56, 0x4d, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x50, 0x75, 0x62,
	0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x12, 0x47, 0x0a, 0x0d, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73,
	0x68, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x18, 0x2e, 0x76, 0x6d, 0x5f, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x56, 0x4d, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x4d, 0x6f, 0x64, 0x75, 0x6c,
	0x65, 0x1a, 0x1a, 0x2e, 0x76, 0x6d, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x4d, 0x45, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32,
	0x5b, 0x0a, 0x10, 0x56, 0x4d, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x45, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x6f, 0x72, 0x12, 0x47, 0x0a, 0x0d, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x53, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x12, 0x18, 0x2e, 0x76, 0x6d, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x56,
	0x4d, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x1a, 0x1a,
	0x2e, 0x76, 0x6d, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x4d, 0x45, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0x4a, 0x0a, 0x0a,
	0x56, 0x4d, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72, 0x12, 0x3c, 0x0a, 0x07, 0x43, 0x6f,
	0x6d, 0x70, 0x69, 0x6c, 0x65, 0x12, 0x13, 0x2e, 0x76, 0x6d, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x1a, 0x1a, 0x2e, 0x76, 0x6d, 0x5f,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x32, 0x62, 0x0a, 0x19, 0x56, 0x4d, 0x4d, 0x75,
	0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x43, 0x6f, 0x6d,
	0x70, 0x69, 0x6c, 0x65, 0x72, 0x12, 0x45, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65,
	0x12, 0x14, 0x2e, 0x76, 0x6d, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x1a, 0x22, 0x2e, 0x76, 0x6d, 0x5f, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x32, 0x4b, 0x0a, 0x10,
	0x56, 0x4d, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x37, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x12, 0x11, 0x2e, 0x76, 0x6d, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x4d, 0x53, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x1a, 0x12, 0x2e, 0x76, 0x6d, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_vm_proto_rawDescOnce sync.Once
	file_vm_proto_rawDescData = file_vm_proto_rawDesc
)

func file_vm_proto_rawDescGZIP() []byte {
	file_vm_proto_rawDescOnce.Do(func() {
		file_vm_proto_rawDescData = protoimpl.X.CompressGZIP(file_vm_proto_rawDescData)
	})
	return file_vm_proto_rawDescData
}

var file_vm_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_vm_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_vm_proto_goTypes = []interface{}{
	(ContractStatus)(0),               // 0: vm_grpc.ContractStatus
	(VMTypeTag)(0),                    // 1: vm_grpc.VMTypeTag
	(LcsType)(0),                      // 2: vm_grpc.LcsType
	(VmWriteOp)(0),                    // 3: vm_grpc.VmWriteOp
	(*VMStatus)(nil),                  // 4: vm_grpc.VMStatus
	(*StructIdent)(nil),               // 5: vm_grpc.StructIdent
	(*LcsTag)(nil),                    // 6: vm_grpc.LcsTag
	(*ModuleIdent)(nil),               // 7: vm_grpc.ModuleIdent
	(*VMEvent)(nil),                   // 8: vm_grpc.VMEvent
	(*VMAccessPath)(nil),              // 9: vm_grpc.VMAccessPath
	(*VMValue)(nil),                   // 10: vm_grpc.VMValue
	(*VMArgs)(nil),                    // 11: vm_grpc.VMArgs
	(*VMPublishModule)(nil),           // 12: vm_grpc.VMPublishModule
	(*VMExecuteScript)(nil),           // 13: vm_grpc.VMExecuteScript
	(*VMExecuteResponse)(nil),         // 14: vm_grpc.VMExecuteResponse
	(*SourceFile)(nil),                // 15: vm_grpc.SourceFile
	(*CompilationUnit)(nil),           // 16: vm_grpc.CompilationUnit
	(*SourceFiles)(nil),               // 17: vm_grpc.SourceFiles
	(*CompiledUnit)(nil),              // 18: vm_grpc.CompiledUnit
	(*MultipleCompilationResult)(nil), // 19: vm_grpc.MultipleCompilationResult
	(*CompilationResult)(nil),         // 20: vm_grpc.CompilationResult
	(*VMScript)(nil),                  // 21: vm_grpc.VMScript
	(*Signature)(nil),                 // 22: vm_grpc.Signature
}
var file_vm_proto_depIdxs = []int32{
	6,  // 0: vm_grpc.StructIdent.type_params:type_name -> vm_grpc.LcsTag
	2,  // 1: vm_grpc.LcsTag.type_tag:type_name -> vm_grpc.LcsType
	6,  // 2: vm_grpc.LcsTag.vector_type:type_name -> vm_grpc.LcsTag
	5,  // 3: vm_grpc.LcsTag.struct_ident:type_name -> vm_grpc.StructIdent
	7,  // 4: vm_grpc.VMEvent.sender_module:type_name -> vm_grpc.ModuleIdent
	6,  // 5: vm_grpc.VMEvent.event_type:type_name -> vm_grpc.LcsTag
	3,  // 6: vm_grpc.VMValue.type:type_name -> vm_grpc.VmWriteOp
	9,  // 7: vm_grpc.VMValue.path:type_name -> vm_grpc.VMAccessPath
	1,  // 8: vm_grpc.VMArgs.type:type_name -> vm_grpc.VMTypeTag
	5,  // 9: vm_grpc.VMExecuteScript.type_params:type_name -> vm_grpc.StructIdent
	11, // 10: vm_grpc.VMExecuteScript.args:type_name -> vm_grpc.VMArgs
	10, // 11: vm_grpc.VMExecuteResponse.write_set:type_name -> vm_grpc.VMValue
	8,  // 12: vm_grpc.VMExecuteResponse.events:type_name -> vm_grpc.VMEvent
	0,  // 13: vm_grpc.VMExecuteResponse.status:type_name -> vm_grpc.ContractStatus
	4,  // 14: vm_grpc.VMExecuteResponse.statusStruct:type_name -> vm_grpc.VMStatus
	16, // 15: vm_grpc.SourceFiles.units:type_name -> vm_grpc.CompilationUnit
	18, // 16: vm_grpc.MultipleCompilationResult.units:type_name -> vm_grpc.CompiledUnit
	1,  // 17: vm_grpc.Signature.arguments:type_name -> vm_grpc.VMTypeTag
	12, // 18: vm_grpc.VMModulePublisher.PublishModule:input_type -> vm_grpc.VMPublishModule
	13, // 19: vm_grpc.VMScriptExecutor.ExecuteScript:input_type -> vm_grpc.VMExecuteScript
	15, // 20: vm_grpc.VMCompiler.Compile:input_type -> vm_grpc.SourceFile
	17, // 21: vm_grpc.VMMultipleSourcesCompiler.Compile:input_type -> vm_grpc.SourceFiles
	21, // 22: vm_grpc.VMScriptMetadata.GetSignature:input_type -> vm_grpc.VMScript
	14, // 23: vm_grpc.VMModulePublisher.PublishModule:output_type -> vm_grpc.VMExecuteResponse
	14, // 24: vm_grpc.VMScriptExecutor.ExecuteScript:output_type -> vm_grpc.VMExecuteResponse
	20, // 25: vm_grpc.VMCompiler.Compile:output_type -> vm_grpc.CompilationResult
	19, // 26: vm_grpc.VMMultipleSourcesCompiler.Compile:output_type -> vm_grpc.MultipleCompilationResult
	22, // 27: vm_grpc.VMScriptMetadata.GetSignature:output_type -> vm_grpc.Signature
	23, // [23:28] is the sub-list for method output_type
	18, // [18:23] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_vm_proto_init() }
func file_vm_proto_init() {
	if File_vm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VMStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StructIdent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LcsTag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vm_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModuleIdent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vm_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VMEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vm_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VMAccessPath); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vm_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VMValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vm_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VMArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vm_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VMPublishModule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vm_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VMExecuteScript); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vm_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VMExecuteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vm_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SourceFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vm_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompilationUnit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vm_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SourceFiles); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vm_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompiledUnit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vm_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultipleCompilationResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vm_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompilationResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vm_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VMScript); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vm_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Signature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vm_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_vm_proto_goTypes,
		DependencyIndexes: file_vm_proto_depIdxs,
		EnumInfos:         file_vm_proto_enumTypes,
		MessageInfos:      file_vm_proto_msgTypes,
	}.Build()
	File_vm_proto = out.File
	file_vm_proto_rawDesc = nil
	file_vm_proto_goTypes = nil
	file_vm_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// VMModulePublisherClient is the client API for VMModulePublisher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VMModulePublisherClient interface {
	PublishModule(ctx context.Context, in *VMPublishModule, opts ...grpc.CallOption) (*VMExecuteResponse, error)
}

type vMModulePublisherClient struct {
	cc grpc.ClientConnInterface
}

func NewVMModulePublisherClient(cc grpc.ClientConnInterface) VMModulePublisherClient {
	return &vMModulePublisherClient{cc}
}

func (c *vMModulePublisherClient) PublishModule(ctx context.Context, in *VMPublishModule, opts ...grpc.CallOption) (*VMExecuteResponse, error) {
	out := new(VMExecuteResponse)
	err := c.cc.Invoke(ctx, "/vm_grpc.VMModulePublisher/PublishModule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VMModulePublisherServer is the server API for VMModulePublisher service.
type VMModulePublisherServer interface {
	PublishModule(context.Context, *VMPublishModule) (*VMExecuteResponse, error)
}

// UnimplementedVMModulePublisherServer can be embedded to have forward compatible implementations.
type UnimplementedVMModulePublisherServer struct {
}

func (*UnimplementedVMModulePublisherServer) PublishModule(context.Context, *VMPublishModule) (*VMExecuteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishModule not implemented")
}

func RegisterVMModulePublisherServer(s *grpc.Server, srv VMModulePublisherServer) {
	s.RegisterService(&_VMModulePublisher_serviceDesc, srv)
}

func _VMModulePublisher_PublishModule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMPublishModule)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMModulePublisherServer).PublishModule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vm_grpc.VMModulePublisher/PublishModule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMModulePublisherServer).PublishModule(ctx, req.(*VMPublishModule))
	}
	return interceptor(ctx, in, info, handler)
}

var _VMModulePublisher_serviceDesc = grpc.ServiceDesc{
	ServiceName: "vm_grpc.VMModulePublisher",
	HandlerType: (*VMModulePublisherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishModule",
			Handler:    _VMModulePublisher_PublishModule_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vm.proto",
}

// VMScriptExecutorClient is the client API for VMScriptExecutor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VMScriptExecutorClient interface {
	ExecuteScript(ctx context.Context, in *VMExecuteScript, opts ...grpc.CallOption) (*VMExecuteResponse, error)
}

type vMScriptExecutorClient struct {
	cc grpc.ClientConnInterface
}

func NewVMScriptExecutorClient(cc grpc.ClientConnInterface) VMScriptExecutorClient {
	return &vMScriptExecutorClient{cc}
}

func (c *vMScriptExecutorClient) ExecuteScript(ctx context.Context, in *VMExecuteScript, opts ...grpc.CallOption) (*VMExecuteResponse, error) {
	out := new(VMExecuteResponse)
	err := c.cc.Invoke(ctx, "/vm_grpc.VMScriptExecutor/ExecuteScript", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VMScriptExecutorServer is the server API for VMScriptExecutor service.
type VMScriptExecutorServer interface {
	ExecuteScript(context.Context, *VMExecuteScript) (*VMExecuteResponse, error)
}

// UnimplementedVMScriptExecutorServer can be embedded to have forward compatible implementations.
type UnimplementedVMScriptExecutorServer struct {
}

func (*UnimplementedVMScriptExecutorServer) ExecuteScript(context.Context, *VMExecuteScript) (*VMExecuteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteScript not implemented")
}

func RegisterVMScriptExecutorServer(s *grpc.Server, srv VMScriptExecutorServer) {
	s.RegisterService(&_VMScriptExecutor_serviceDesc, srv)
}

func _VMScriptExecutor_ExecuteScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMExecuteScript)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMScriptExecutorServer).ExecuteScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vm_grpc.VMScriptExecutor/ExecuteScript",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMScriptExecutorServer).ExecuteScript(ctx, req.(*VMExecuteScript))
	}
	return interceptor(ctx, in, info, handler)
}

var _VMScriptExecutor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "vm_grpc.VMScriptExecutor",
	HandlerType: (*VMScriptExecutorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteScript",
			Handler:    _VMScriptExecutor_ExecuteScript_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vm.proto",
}

// VMCompilerClient is the client API for VMCompiler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VMCompilerClient interface {
	Compile(ctx context.Context, in *SourceFile, opts ...grpc.CallOption) (*CompilationResult, error)
}

type vMCompilerClient struct {
	cc grpc.ClientConnInterface
}

func NewVMCompilerClient(cc grpc.ClientConnInterface) VMCompilerClient {
	return &vMCompilerClient{cc}
}

func (c *vMCompilerClient) Compile(ctx context.Context, in *SourceFile, opts ...grpc.CallOption) (*CompilationResult, error) {
	out := new(CompilationResult)
	err := c.cc.Invoke(ctx, "/vm_grpc.VMCompiler/Compile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VMCompilerServer is the server API for VMCompiler service.
type VMCompilerServer interface {
	Compile(context.Context, *SourceFile) (*CompilationResult, error)
}

// UnimplementedVMCompilerServer can be embedded to have forward compatible implementations.
type UnimplementedVMCompilerServer struct {
}

func (*UnimplementedVMCompilerServer) Compile(context.Context, *SourceFile) (*CompilationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Compile not implemented")
}

func RegisterVMCompilerServer(s *grpc.Server, srv VMCompilerServer) {
	s.RegisterService(&_VMCompiler_serviceDesc, srv)
}

func _VMCompiler_Compile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SourceFile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMCompilerServer).Compile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vm_grpc.VMCompiler/Compile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMCompilerServer).Compile(ctx, req.(*SourceFile))
	}
	return interceptor(ctx, in, info, handler)
}

var _VMCompiler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "vm_grpc.VMCompiler",
	HandlerType: (*VMCompilerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Compile",
			Handler:    _VMCompiler_Compile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vm.proto",
}

// VMMultipleSourcesCompilerClient is the client API for VMMultipleSourcesCompiler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VMMultipleSourcesCompilerClient interface {
	Compile(ctx context.Context, in *SourceFiles, opts ...grpc.CallOption) (*MultipleCompilationResult, error)
}

type vMMultipleSourcesCompilerClient struct {
	cc grpc.ClientConnInterface
}

func NewVMMultipleSourcesCompilerClient(cc grpc.ClientConnInterface) VMMultipleSourcesCompilerClient {
	return &vMMultipleSourcesCompilerClient{cc}
}

func (c *vMMultipleSourcesCompilerClient) Compile(ctx context.Context, in *SourceFiles, opts ...grpc.CallOption) (*MultipleCompilationResult, error) {
	out := new(MultipleCompilationResult)
	err := c.cc.Invoke(ctx, "/vm_grpc.VMMultipleSourcesCompiler/Compile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VMMultipleSourcesCompilerServer is the server API for VMMultipleSourcesCompiler service.
type VMMultipleSourcesCompilerServer interface {
	Compile(context.Context, *SourceFiles) (*MultipleCompilationResult, error)
}

// UnimplementedVMMultipleSourcesCompilerServer can be embedded to have forward compatible implementations.
type UnimplementedVMMultipleSourcesCompilerServer struct {
}

func (*UnimplementedVMMultipleSourcesCompilerServer) Compile(context.Context, *SourceFiles) (*MultipleCompilationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Compile not implemented")
}

func RegisterVMMultipleSourcesCompilerServer(s *grpc.Server, srv VMMultipleSourcesCompilerServer) {
	s.RegisterService(&_VMMultipleSourcesCompiler_serviceDesc, srv)
}

func _VMMultipleSourcesCompiler_Compile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SourceFiles)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMMultipleSourcesCompilerServer).Compile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vm_grpc.VMMultipleSourcesCompiler/Compile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMMultipleSourcesCompilerServer).Compile(ctx, req.(*SourceFiles))
	}
	return interceptor(ctx, in, info, handler)
}

var _VMMultipleSourcesCompiler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "vm_grpc.VMMultipleSourcesCompiler",
	HandlerType: (*VMMultipleSourcesCompilerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Compile",
			Handler:    _VMMultipleSourcesCompiler_Compile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vm.proto",
}

// VMScriptMetadataClient is the client API for VMScriptMetadata service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VMScriptMetadataClient interface {
	GetSignature(ctx context.Context, in *VMScript, opts ...grpc.CallOption) (*Signature, error)
}

type vMScriptMetadataClient struct {
	cc grpc.ClientConnInterface
}

func NewVMScriptMetadataClient(cc grpc.ClientConnInterface) VMScriptMetadataClient {
	return &vMScriptMetadataClient{cc}
}

func (c *vMScriptMetadataClient) GetSignature(ctx context.Context, in *VMScript, opts ...grpc.CallOption) (*Signature, error) {
	out := new(Signature)
	err := c.cc.Invoke(ctx, "/vm_grpc.VMScriptMetadata/GetSignature", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VMScriptMetadataServer is the server API for VMScriptMetadata service.
type VMScriptMetadataServer interface {
	GetSignature(context.Context, *VMScript) (*Signature, error)
}

// UnimplementedVMScriptMetadataServer can be embedded to have forward compatible implementations.
type UnimplementedVMScriptMetadataServer struct {
}

func (*UnimplementedVMScriptMetadataServer) GetSignature(context.Context, *VMScript) (*Signature, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSignature not implemented")
}

func RegisterVMScriptMetadataServer(s *grpc.Server, srv VMScriptMetadataServer) {
	s.RegisterService(&_VMScriptMetadata_serviceDesc, srv)
}

func _VMScriptMetadata_GetSignature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMScript)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMScriptMetadataServer).GetSignature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vm_grpc.VMScriptMetadata/GetSignature",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMScriptMetadataServer).GetSignature(ctx, req.(*VMScript))
	}
	return interceptor(ctx, in, info, handler)
}

var _VMScriptMetadata_serviceDesc = grpc.ServiceDesc{
	ServiceName: "vm_grpc.VMScriptMetadata",
	HandlerType: (*VMScriptMetadataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSignature",
			Handler:    _VMScriptMetadata_GetSignature_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vm.proto",
}
