name: Go
on:
  pull_request:
  push:
    branches:
    - master

jobs:
  rust:
    name: Go
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        go-version:
        - 1.15.10
        os:
        - ubuntu-latest
        - windows-latest
        # - macos-latest

    env:
      GO111MODULE: on
      GOPATH: ${{ github.workspace }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Go toolchain
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install Protoc
      uses: arduino/setup-protoc@master
      with:
        version: '3.x'

    - name: chmod Protoc
      shell: bash
      run: "chmod +x `which protoc`"

    - name: Restore dependencies from cache
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install dependencies
      shell: bash
      run: go get -u github.com/golang/protobuf/protoc-gen-go && go get -u google.golang.org/grpc

    - name: Build
      shell: bash
      run: make
